# https://docs.travis-ci.com/user/customizing-the-build/

if: tag IS blank
os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
cache:
  yarn: true
install:
  - yarn install
  - yarn add rxjs@6
script:
  - node --version
  - npm --version
  - yarn --version
  - yarn run dist
