# https://docs.travis-ci.com/user/customizing-the-build/

branches:
  only:
    - master
os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "lts/*"
  - "8"
  - "10"
  - "11"
cache:
  yarn: true
before_install:
  - | # installing the most recent yarn version
    curl -o- -L https://yarnpkg.com/install.sh | bash;
    export PATH="$HOME/.yarn/bin:$PATH";
install:
  - yarn --pure-lockfile
  - yarn add rxjs@6
script:
  - node --version
  - npm --version
  - yarn --version
  - yarn run lib
